# Netlify Configuration for مداوم (Modawim) Landing Page

[build]
  # No build command needed for static site
  publish = "."

[[headers]]
  # Set headers for download files
  for = "/downloads/*"
  [headers.values]
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=604800"

[[headers]]
  # Set headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules (if needed)
[[redirects]]
  from = "/download"
  to = "/#download"
  status = 301

# 404 handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
